### ISSUE TITLE
TypeError: 'NoneType' object does not support item assignment

### ISSUE THREAD

**Issue by hesic73** [rock-simulation/phobos#369]
No informative error message, no detailed bug report. But I suspect this is because phobos doesn't support importing .glb files.

```
Python: Traceback (most recent call last):
  File "/home/sichengh/.config/blender/3.3/scripts/addons/phobos/blender/operators/io.py", line 324, in execute
    createRobot(robot)
  File "/home/sichengh/.config/blender/3.3/scripts/addons/phobos/blender/io/phobos2blender.py", line 549, in createRobot
    newlink = createLink(link)
  File "/home/sichengh/.config/blender/3.3/scripts/addons/phobos/blender/io/phobos2blender.py", line 210, in createLink
    geom = createGeometry(viscol, 'visual')
  File "/home/sichengh/.config/blender/3.3/scripts/addons/phobos/blender/io/phobos2blender.py", line 82, in createGeometry
    newgeom.data = geometry.load_mesh()
  File "/home/sichengh/.config/blender/3.3/scripts/addons/phobos/io/representation.py", line 870, in load_mesh
    self._mesh_object["input_file"] = self.input_file
TypeError: 'NoneType' object does not support item assignment
```

**Comment by mirkow** [comment]
I have the same error when using a glb mesh file. Would be great to have glb support. Blender itself can import the glb files.

**Comment by AlpenAalAlex** [comment]
@hesic73 @mirkow I added glb as supported mesh type with the above commit. Does this address your issue?

**Comment by hesic73** [comment]
Thanks for the quick fix! I can't find the original URDF to test it now, but the update looks great. Appreciate it!
